name: Verify markdown links in Kyma project

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  verify-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install 
        run: npm install
      
      - name: Checkout kyma-project/kyma
        uses: actions/checkout@v3
        with:
          repository: kyma-project/kyma
          path: kyma

      - name: Checkout kyma-project/btp-manager
        uses: actions/checkout@v3
        with:
          repository: kyma-project/btp-manager
          path: btp-manager

      - name: Checkout kyma-project/istio
        uses: actions/checkout@v3
        with:
          repository: kyma-project/istio
          path: istio 
      - name: Checkout kyma-project/serverless-manager
        uses: actions/checkout@v3
        with:
          repository: kyma-project/serverless-manager
          path: serverless-manager

      - name: Checkout kyma-project/telemetry-manager
        uses: actions/checkout@v3
        with:
          repository: kyma-project/telemetry-manager
          path: telemetry-manager 
      - name: Checkout kyma-project/eventing-manager
        uses: actions/checkout@v3
        with:
          repository: kyma-project/eventing-manager
          path: eventing-manager  
      - name: Checkout kyma-project/api-gateway
        uses: actions/checkout@v3
        with:
          repository: kyma-project/api-gateway
          path: api-gateway 
      - name: Checkout kyma-project/nats-manager  
        uses: actions/checkout@v3
        with:
          repository: kyma-project/nats-manager
          path: nats-manager  
      - name: Checkout kyma-project/application-connector-manager
        uses: actions/checkout@v3
        with:
          repository: kyma-project/application-connector-manager
          path: application-connector-manager 
      - name: Checkout kyma-project/keda-manager  
        uses: actions/checkout@v3
        with:
          repository: kyma-project/keda-manager
          path: keda-manager  
      - name: Checkout kyma-project/community 
        uses: actions/checkout@v3
        with:
          repository: kyma-project/community
          path: community
            
      - name: Verify links
        run: |
          node md-check-link.js -q -n 8 -c .mlc.config.json ./kyma/docs ./btp-manager/docs ./istio/docs ./serverless-manager/docs ./telemetry-manager/docs ./eventing-manager/docs ./api-gateway/docs ./nats-manager/docs ./application-connector-manager/docs ./keda-manager/docs ./community/docs
