name: Verify markdown links in Kyma project

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  help-portal-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install 
        run: npm install
      - name: Checkout ${{matrix.repository}}
        uses: actions/checkout@v4
        with:
          repository: SAP-docs/btp-cloud-platform
          path: btp-cloud-platform
      - name: Verify links
        run: |
          cd btp-cloud-platform
          node ../md-check-link.js -q -n 8 -c ../.mlc.config.json ./docs
